Introducing RSTUF-TAC
repository-service-tuf/repository-service-tuf pull request #430
Opened 2023-08-23 14:51 UTC by kairoaraujo

Empowering the participation from TUF, OpenSSF, and public repository maintainers. This initiative aims to give them a stronger voice in shaping the direction of the RSTUF project. The ultimate goal is to establish RSTUF as a neutral project with widespread benefits.

2023-08-24 08:45 UTC, lukpueh submitted a review, later dismissed
Looks great! Is it not yet included in `docs/source/devel/index.rst` on purpose?

2023-08-24 09:06 UTC, kairoaraujo commented
Yes. It will be included on https://repository-service-tuf.readthedocs.io as well 😄

2023-08-24 09:08 UTC, lukpueh commented
> Yes. It will be included on https://repository-service-tuf.readthedocs.io as well 😄

That's what I figured. But it isn't included yet. You'll need to add it to some toctree first.

2023-09-01 14:48 UTC, MVrachev submitted a review, later dismissed

2023-09-04 10:37 UTC, MVrachev requested changes

2023-09-04 10:37 UTC, MVrachev commented on TAC.rst
> +    behavior, etc., have high-priority on user/repository features.
```suggestion
    behavior, etc., have higher priority over user/repository features.
```

2023-09-04 10:37 UTC, MVrachev commented on TAC.rst
> +expertise on software repository design, to make recommendations and guide the
```suggestion
expertise in software repository design, to make recommendations and guide the
```

2023-09-04 10:37 UTC, MVrachev commented on TAC.rst
> +      - @MVrachev
We need to add @lukpueh and @KAUTH  as well and make it clear that all of us as RSTUF maintainers can have 1 vote.
Also, let's make it clear that one can be a representative in multiple organizations, but can vote as a representative of one of them. That is logical, but is important to note. For example, even though @lukpueh is an RSTUF maintainer he can join as a voting member on behalf of TUF, but won't vote as an RSTUF maintainer.

2023-09-04 11:28 UTC, MVrachev approved these changes

2023-09-04 11:32 UTC, merged